version: "3"
services:
  nodejs:
    container_name: lamp_node
    build: 
      context: ./docker/nodejs
    ports: 
      - ${PORT_NODE_WEB}:3030
    networks: 
      - lamp
    depends_on: 
      - db
  web:
    container_name: lamp_web
    build:
      context: ./docker/apache
      args:
        php_version: ${PHP_VERSION}
    volumes:
      - ./DocumentRoot:/app
      - ./docker/apache/errors:/errors
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - ${PORT_HTTP}:80
      - ${PORT_HTTPS}:443
    networks:
      - lamp
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    container_name: lamp_mailhog
    ports:
      - ${PORT_MAILHOG_HTTP}:8025
      - ${PORT_MAILHOG_SMTP}:1025
    networks:
      - lamp
  db:
    container_name: lamp_db
    image: mysql:8.0
    ports:
      - ${PORT_SQL}:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - lamp
    environment:
      TZ: ${TZ}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin:
    container_name: lamp_pmd
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
    - ${PORT_PHPMYADM}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - lamp
  redis:
    image: "redis:alpine"
    container_name: lamp_redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - lamp

volumes:
  persistent:
  redis-data:

networks:
  lamp: