version: "3"
services:
  web:
    container_name: lamp_web
    build:
      context: ./docker/apache
    volumes:
      - ./DocumentRoot:/app
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - ${PORT_HTTP}:80
    networks:
      - lamp
    depends_on:
      - db
  mailhog:
    image: mailhog/mailhog
    ports:
      - ${PORT_MAILHOG_HTTP}:8025
    networks:
      - lamp
  db:
    container_name: lamp_db
    image: mysql:8.0
    ports:
      - ${PORT_SQL}:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - lamp
    environment:
      TZ: ${TZ}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  phpmyadmin:
    container_name: lamp_pmd
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
    - ${PORT_PHPMYADM}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - lamp
volumes:
  persistent:
networks:
  lamp:


